import React from "react";
import { Link } from "react-router-dom";

const CONTACT_EMAIL = "memeclassroom@gmail.com";
const LAST_UPDATED = "September 2026";

const Section = ({ title, children }) => (
  <section className="space-y-3">
    <h2 className="text-lg font-extrabold text-gray-900 dark:text-white border-b border-gray-200 dark:border-zinc-800 pb-2">
      {title}
    </h2>
    <div className="text-sm text-gray-600 dark:text-gray-300 leading-relaxed space-y-3">
      {children}
    </div>
  </section>
);

const PrivacyPolicy = () => {
  return (
    <div className="max-w-3xl mx-auto py-10 px-4 space-y-10">
      {/* Header */}
      <div className="space-y-2">
        <span className="bg-purple-100 dark:bg-purple-950/40 text-purple-700 dark:text-purple-300 text-xs font-bold uppercase tracking-wider px-3 py-1.5 rounded-lg">
          Legal
        </span>
        <h1 className="text-3xl font-black tracking-tight text-gray-900 dark:text-white mt-2">
          Privacy Policy
        </h1>
        <p className="text-sm text-gray-500 dark:text-gray-400">
          Last updated: {LAST_UPDATED}
        </p>
        <p className="text-sm text-gray-600 dark:text-gray-300 leading-relaxed">
          This Privacy Policy describes how MemeClassroom ("<strong>we</strong>", "<strong>our</strong>", or "
          <strong>the platform</strong>") collects, uses, and protects information when you use our website and services.
          By using MemeClassroom, you agree to the practices described in this policy.
        </p>
      </div>

      {/* 1 */}
      <Section title="1. Who We Are">
        <p>
          MemeClassroom is an open educational platform built for teachers and students. It allows educators to create,
          share, and discuss educational memes grounded in open pedagogy principles. The platform is operated as an
          independent, non-commercial project.
        </p>
        <p>
          Contact: <a href={`mailto:${CONTACT_EMAIL}`} className="text-purple-600 dark:text-purple-400 hover:underline">{CONTACT_EMAIL}</a>
        </p>
      </Section>

      {/* 2 */}
      <Section title="2. Information We Collect">
        <p><strong>Information you provide when registering:</strong></p>
        <ul className="list-disc pl-5 space-y-1">
          <li>Name (display name)</li>
          <li>Email address</li>
          <li>Password (handled by Firebase Authentication — we never see or store raw passwords)</li>
          <li>Role (student, teacher, expert)</li>
          <li>Institution name</li>
          <li>Location (country / state / city, self-reported)</li>
          <li>Profile avatar (selected from preset options or uploaded image)</li>
          <li>ID card or institutional document (uploaded by teachers applying for verified status — <strong>see §5</strong>)</li>
        </ul>

        <p><strong>Information generated by your activity:</strong></p>
        <ul className="list-disc pl-5 space-y-1">
          <li>Memes you create and publish</li>
          <li>Comments and replies you write</li>
          <li>Staffroom posts and discussions</li>
          <li>Resources you contribute</li>
          <li>Memes or resources you bookmark</li>
          <li>Meme literacy test scores and badge achievements</li>
          <li>Likes, ratings, and flags you submit</li>
          <li>Notification history</li>
        </ul>

        <p><strong>Information stored only in your browser (never sent to our servers):</strong></p>
        <ul className="list-disc pl-5 space-y-1">
          <li>Accessibility and display preferences (high contrast, font size, screen reader settings)</li>
          <li>Your personal Gemini AI API key, if you provide one</li>
          <li>AI usage quota tracking</li>
        </ul>

        <p><strong>We do not collect:</strong> payment information, precise GPS location, device identifiers, or browsing history from other sites.</p>
      </Section>

      {/* 3 */}
      <Section title="3. How We Use Your Information">
        <ul className="list-disc pl-5 space-y-1">
          <li>To provide and operate the platform (creating your account, displaying your profile, enabling meme creation)</li>
          <li>To send in-app notifications about activity related to your content (comments, likes, badges)</li>
          <li>To display your public contributions in the Meme Library, Staffroom, and Resources sections</li>
          <li>To verify teacher/expert applications (via Admin review of submitted credentials)</li>
          <li>To enforce community guidelines and respond to reported content</li>
          <li>To improve the platform based on aggregate usage patterns (not individually tracked)</li>
        </ul>
        <p>We do not sell your data. We do not use your data for advertising.</p>
      </Section>

      {/* 4 */}
      <Section title="4. Who Can See Your Information">
        <p>
          <strong>Your profile</strong> (name, role, institution, country, avatar) is visible to other signed-in users
          of the platform. It is not visible to unauthenticated visitors.
        </p>
        <p>
          <strong>Your email address</strong> is visible to platform administrators only. It is not displayed publicly.
        </p>
        <p>
          <strong>Memes you publish</strong> as "public" are visible to all users (including unauthenticated visitors browsing the Library).
          Memes you save as drafts are visible only to you and administrators.
        </p>
        <p>
          <strong>Comments, Staffroom posts, and resources</strong> are visible to signed-in users.
        </p>
        <p>
          <strong>Your literacy test results, bookmarks, and badges</strong> are visible only to you and administrators.
        </p>
      </Section>

      {/* 5 */}
      <Section title="5. ID Card and Verification Documents">
        <p>
          Teachers applying for verified "Expert" status may optionally upload an institutional ID card or similar
          credential document. This document is:
        </p>
        <ul className="list-disc pl-5 space-y-1">
          <li>Stored in Firebase Storage in a restricted folder</li>
          <li>Accessible only to platform administrators for verification purposes</li>
          <li>Not publicly visible or shared with other users</li>
          <li>Deleted upon request — contact us at <a href={`mailto:${CONTACT_EMAIL}`} className="text-purple-600 dark:text-purple-400 hover:underline">{CONTACT_EMAIL}</a></li>
        </ul>
        <p>
          Uploading an ID document is entirely optional and is only used to determine eligibility for the Expert role.
        </p>
      </Section>

      {/* 6 */}
      <Section title="6. Third-Party Services">
        <p>MemeClassroom uses the following third-party services, each with their own privacy policies:</p>
        <ul className="list-disc pl-5 space-y-2">
          <li>
            <strong>Firebase (Google)</strong> — Authentication, database (Firestore), file storage, and Cloud Functions.
            Your data is stored on Google's infrastructure.{" "}
            <a href="https://firebase.google.com/support/privacy" target="_blank" rel="noopener noreferrer" className="text-purple-600 dark:text-purple-400 hover:underline">Firebase Privacy Policy ↗</a>
          </li>
          <li>
            <strong>Giphy</strong> — GIF search in the Meme Lab. When you search for GIFs, your search query is sent
            to Giphy's servers.{" "}
            <a href="https://support.giphy.com/hc/en-us/articles/360032872931" target="_blank" rel="noopener noreferrer" className="text-purple-600 dark:text-purple-400 hover:underline">Giphy Privacy Policy ↗</a>
          </li>
          <li>
            <strong>Google Gemini API</strong> — AI-powered caption generation in the Meme Lab. If you use the AI
            caption feature (with your own API key), the meme content and your prompt are sent to Google's Gemini API.{" "}
            <a href="https://ai.google.dev/gemini-api/terms" target="_blank" rel="noopener noreferrer" className="text-purple-600 dark:text-purple-400 hover:underline">Google AI Terms ↗</a>
          </li>
          <li>
            <strong>corsproxy.io</strong> — An external CORS proxy service used to enable image download and export
            features. Image URLs from Firebase Storage are routed through this service for technical reasons. We do
            not control this third party.
          </li>
        </ul>
      </Section>

      {/* 7 */}
      <Section title="7. Data Retention">
        <p>
          Your account data and content are retained as long as your account is active. If you delete your account,
          your profile data will be removed. Published memes and comments may persist in anonymised form unless you
          request their deletion separately.
        </p>
        <p>
          To request deletion of your data, contact us at{" "}
          <a href={`mailto:${CONTACT_EMAIL}`} className="text-purple-600 dark:text-purple-400 hover:underline">{CONTACT_EMAIL}</a>.
        </p>
      </Section>

      {/* 8 */}
      <Section title="8. Children's Privacy">
        <p>
          MemeClassroom is intended for use by educators and their students. If students under the age of 13 (in the
          United States) or 16 (in the EU) use the platform, this must be done under the supervision of a teacher or
          parent/guardian who has registered an account on their behalf.
        </p>
        <p>
          We do not knowingly collect personal information from children under 13 without verifiable parental consent.
          If you believe we have inadvertently collected such information, please contact us immediately.
        </p>
      </Section>

      {/* 9 */}
      <Section title="9. Cookies and Local Storage">
        <p>
          MemeClassroom does not use advertising cookies or third-party tracking cookies. Firebase Authentication
          stores your session using <code className="bg-gray-100 dark:bg-zinc-800 px-1 rounded text-xs">IndexedDB</code> in
          your browser (not HTTP cookies). Accessibility preferences and AI key data are stored in browser localStorage
          and are never transmitted to our servers.
        </p>
      </Section>

      {/* 10 */}
      <Section title="10. Your Rights">
        <p>Depending on your location, you may have the right to:</p>
        <ul className="list-disc pl-5 space-y-1">
          <li>Access the personal data we hold about you</li>
          <li>Correct inaccurate data (you can edit your profile directly)</li>
          <li>Request deletion of your account and associated data</li>
          <li>Object to or restrict certain processing</li>
          <li>Data portability (export of your content)</li>
        </ul>
        <p>
          To exercise any of these rights, contact:{" "}
          <a href={`mailto:${CONTACT_EMAIL}`} className="text-purple-600 dark:text-purple-400 hover:underline">{CONTACT_EMAIL}</a>
        </p>
      </Section>

      {/* 11 */}
      <Section title="11. Changes to This Policy">
        <p>
          We may update this Privacy Policy from time to time. When we do, the "Last updated" date at the top of this
          page will change. Continued use of the platform after changes are posted constitutes acceptance of the updated policy.
        </p>
      </Section>

      {/* Back link */}
      <div className="pt-4 border-t border-gray-200 dark:border-zinc-800 text-sm">
        <Link to="/" className="text-purple-600 dark:text-purple-400 hover:underline font-semibold">
          ← Back to MemeClassroom
        </Link>
        {" · "}
        <Link to="/terms" className="text-purple-600 dark:text-purple-400 hover:underline font-semibold">
          Terms of Service
        </Link>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
